import './js/header-mobi-menu';
import './js/categories';
import './js/exercise-filter';
import './js/favorites-block';
import './js/modal-exercise';
import './js/modal-rating';
import './js/footer';
import './js/quote';
import './js/scrollup';